;;;; Copyright (c) 2024-2026 Parkian Company LLC. All rights reserved.
;;;; SPDX-License-Identifier: BSD-3-Clause

;;;; cl-compliance - Transaction Monitoring
;;;; Transaction monitoring rules and alerts

(in-package #:cl-compliance)

;;; ============================================================================
;;; Rule Types
;;; ============================================================================

(defconstant +rule-type-threshold+ :threshold
  "Threshold-based rule (amount exceeds limit).")

(defconstant +rule-type-velocity+ :velocity
  "Velocity rule (frequency of transactions).")

(defconstant +rule-type-pattern+ :pattern
  "Pattern-based rule (matching transaction patterns).")

(defconstant +rule-type-behavioral+ :behavioral
  "Behavioral rule (deviation from baseline).")

(defconstant +rule-type-geographic+ :geographic
  "Geographic rule (high-risk locations).")

;;; ============================================================================
;;; Alert Statuses
;;; ============================================================================

(defconstant +alert-status-new+ :new)
(defconstant +alert-status-investigating+ :investigating)
(defconstant +alert-status-escalated+ :escalated)
(defconstant +alert-status-resolved-true-positive+ :resolved-true-positive)
(defconstant +alert-status-resolved-false-positive+ :resolved-false-positive)

;;; ============================================================================
;;; Monitoring Structures
;;; ============================================================================

(defstruct monitoring-rule
  "A transaction monitoring rule."
  (id "" :type string)
  (name "" :type string)
  (description "" :type string)
  (type :threshold :type keyword)
  (conditions '() :type list)
  (actions '() :type list)
  (severity :medium :type keyword)
  (enabled t :type boolean)
  (created-at 0 :type integer)
  (updated-at 0 :type integer))

(defstruct monitoring-alert
  "An alert generated by transaction monitoring."
  (id "" :type string)
  (rule-id "" :type string)
  (transaction-id "" :type string)
  (identity-id "" :type string)
  (severity :medium :type keyword)
  (status :new :type keyword)
  (details nil)
  (created-at 0 :type integer)
  (assigned-to "" :type string)
  (resolved-at 0 :type integer)
  (resolution "" :type string))

(defstruct transaction-monitor
  "Transaction monitoring system."
  (rules (make-hash-table :test 'equal) :type hash-table)
  (alerts (make-hash-table :test 'equal) :type hash-table)
  (running nil :type boolean)
  (config (make-hash-table :test 'equal) :type hash-table))

;;; ============================================================================
;;; Monitor Operations
;;; ============================================================================

(defun create-transaction-monitor (&key config)
  "Create a new transaction monitor with default settings."
  (make-transaction-monitor
   :rules (make-hash-table :test 'equal)
   :alerts (make-hash-table :test 'equal)
   :running nil
   :config (or config (make-hash-table :test 'equal))))

(defun start-transaction-monitor (monitor)
  "Start the transaction monitor."
  (setf (transaction-monitor-running monitor) t)
  monitor)

(defun stop-transaction-monitor (monitor)
  "Stop the transaction monitor."
  (setf (transaction-monitor-running monitor) nil)
  monitor)

;;; ============================================================================
;;; Rule Management
;;; ============================================================================

(defun add-monitoring-rule (monitor rule)
  "Add a monitoring rule."
  (when (string= (monitoring-rule-id rule) "")
    (setf (monitoring-rule-id rule) (generate-uuid)))
  (setf (monitoring-rule-created-at rule) (get-universal-time)
        (monitoring-rule-updated-at rule) (get-universal-time))
  (setf (gethash (monitoring-rule-id rule) (transaction-monitor-rules monitor)) rule)
  rule)

(defun update-monitoring-rule (monitor rule-id &key name conditions actions severity enabled)
  "Update a monitoring rule."
  (let ((rule (gethash rule-id (transaction-monitor-rules monitor))))
    (unless rule
      (error 'compliance-error
             :code :rule-not-found
             :message "Monitoring rule not found"))
    (when name (setf (monitoring-rule-name rule) name))
    (when conditions (setf (monitoring-rule-conditions rule) conditions))
    (when actions (setf (monitoring-rule-actions rule) actions))
    (when severity (setf (monitoring-rule-severity rule) severity))
    (when enabled (setf (monitoring-rule-enabled rule) enabled))
    (setf (monitoring-rule-updated-at rule) (get-universal-time))
    rule))

(defun delete-monitoring-rule (monitor rule-id)
  "Delete a monitoring rule."
  (remhash rule-id (transaction-monitor-rules monitor)))

(defun get-monitoring-rules (monitor)
  "Get all monitoring rules."
  (let ((rules '()))
    (maphash (lambda (id rule)
               (declare (ignore id))
               (push rule rules))
             (transaction-monitor-rules monitor))
    rules))

;;; ============================================================================
;;; Transaction Monitoring
;;; ============================================================================

(defun monitor-transaction (monitor transaction)
  "Monitor a single transaction against all rules."
  (unless (transaction-monitor-running monitor)
    (return-from monitor-transaction nil))
  (let ((alerts '()))
    (maphash (lambda (id rule)
               (declare (ignore id))
               (when (monitoring-rule-enabled rule)
                 (let ((result (evaluate-rule rule transaction)))
                   (when (getf result :triggered)
                     (push (create-alert monitor rule transaction result) alerts)))))
             (transaction-monitor-rules monitor))
    alerts))

(defun process-transaction-batch (monitor transactions)
  "Process a batch of transactions."
  (let ((all-alerts '()))
    (dolist (tx transactions)
      (let ((alerts (monitor-transaction monitor tx)))
        (setf all-alerts (append alerts all-alerts))))
    all-alerts))

(defun evaluate-rule (rule transaction)
  "Evaluate a rule against a transaction."
  (let ((conditions (monitoring-rule-conditions rule))
        (triggered nil)
        (details '()))
    (dolist (condition conditions)
      (let ((field (getf condition :field))
            (operator (getf condition :operator))
            (value (getf condition :value))
            (tx-value (getf transaction field)))
        (when (evaluate-condition-simple operator tx-value value)
          (setf triggered t)
          (push (list :field field :tx-value tx-value :threshold value) details))))
    (list :triggered triggered :details details)))

(defun evaluate-condition-simple (operator actual expected)
  "Evaluate a simple condition."
  (case operator
    (:gt (and (numberp actual) (> actual expected)))
    (:gte (and (numberp actual) (>= actual expected)))
    (:lt (and (numberp actual) (< actual expected)))
    (:lte (and (numberp actual) (<= actual expected)))
    (:eq (equal actual expected))
    (:neq (not (equal actual expected)))
    (:contains (and (stringp actual) (search expected actual)))
    (:in (member actual expected :test #'equal))
    (otherwise nil)))

;;; ============================================================================
;;; Alert Management
;;; ============================================================================

(defun create-alert (monitor rule transaction details)
  "Create a monitoring alert."
  (let ((alert (make-monitoring-alert
                :id (generate-uuid)
                :rule-id (monitoring-rule-id rule)
                :transaction-id (or (getf transaction :id) "")
                :identity-id (or (getf transaction :identity-id) "")
                :severity (monitoring-rule-severity rule)
                :status :new
                :details details
                :created-at (get-universal-time))))
    (setf (gethash (monitoring-alert-id alert)
                   (transaction-monitor-alerts monitor))
          alert)
    alert))

(defun assign-alert (monitor alert-id assignee)
  "Assign alert to an investigator."
  (let ((alert (gethash alert-id (transaction-monitor-alerts monitor))))
    (when alert
      (setf (monitoring-alert-assigned-to alert) assignee
            (monitoring-alert-status alert) :investigating))
    alert))

(defun escalate-alert (monitor alert-id)
  "Escalate an alert."
  (let ((alert (gethash alert-id (transaction-monitor-alerts monitor))))
    (when alert
      (setf (monitoring-alert-status alert) :escalated))
    alert))

(defun resolve-alert (monitor alert-id resolution &key notes)
  "Resolve an alert."
  (let ((alert (gethash alert-id (transaction-monitor-alerts monitor))))
    (when alert
      (setf (monitoring-alert-status alert) resolution
            (monitoring-alert-resolved-at alert) (get-universal-time)
            (monitoring-alert-resolution alert) (or notes "")))
    alert))

(defun get-alerts (monitor &key status severity identity-id)
  "Get alerts with optional filters."
  (let ((alerts '()))
    (maphash (lambda (id alert)
               (declare (ignore id))
               (when (and (or (null status) (eq (monitoring-alert-status alert) status))
                          (or (null severity) (eq (monitoring-alert-severity alert) severity))
                          (or (null identity-id)
                              (string= (monitoring-alert-identity-id alert) identity-id)))
                 (push alert alerts)))
             (transaction-monitor-alerts monitor))
    alerts))

(defun get-pending-alerts (monitor)
  "Get all pending (new or investigating) alerts."
  (get-alerts monitor :status :new))
